/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { AccountService } from "../account.service";
import { AccountCreateInput } from "./AccountCreateInput";
import { Account } from "./Account";
import { AccountFindManyArgs } from "./AccountFindManyArgs";
import { AccountWhereUniqueInput } from "./AccountWhereUniqueInput";
import { AccountUpdateInput } from "./AccountUpdateInput";
import { DataRecordFindManyArgs } from "../../dataRecord/base/DataRecordFindManyArgs";
import { DataRecord } from "../../dataRecord/base/DataRecord";
import { DataRecordWhereUniqueInput } from "../../dataRecord/base/DataRecordWhereUniqueInput";

export class AccountControllerBase {
  constructor(protected readonly service: AccountService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Account })
  async createAccount(
    @common.Body() data: AccountCreateInput
  ): Promise<Account> {
    return await this.service.createAccount({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        accountNumber: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Account] })
  @ApiNestedQuery(AccountFindManyArgs)
  async accounts(@common.Req() request: Request): Promise<Account[]> {
    const args = plainToClass(AccountFindManyArgs, request.query);
    return this.service.accounts({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        accountNumber: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Account })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async account(
    @common.Param() params: AccountWhereUniqueInput
  ): Promise<Account | null> {
    const result = await this.service.account({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        accountNumber: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Account })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateAccount(
    @common.Param() params: AccountWhereUniqueInput,
    @common.Body() data: AccountUpdateInput
  ): Promise<Account | null> {
    try {
      return await this.service.updateAccount({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          accountNumber: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Account })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteAccount(
    @common.Param() params: AccountWhereUniqueInput
  ): Promise<Account | null> {
    try {
      return await this.service.deleteAccount({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          accountNumber: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/dataRecords")
  @ApiNestedQuery(DataRecordFindManyArgs)
  async findDataRecords(
    @common.Req() request: Request,
    @common.Param() params: AccountWhereUniqueInput
  ): Promise<DataRecord[]> {
    const query = plainToClass(DataRecordFindManyArgs, request.query);
    const results = await this.service.findDataRecords(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        amount: true,
        dateGenerated: true,

        budgetCategory: {
          select: {
            id: true,
          },
        },

        account: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/dataRecords")
  async connectDataRecords(
    @common.Param() params: AccountWhereUniqueInput,
    @common.Body() body: DataRecordWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      dataRecords: {
        connect: body,
      },
    };
    await this.service.updateAccount({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/dataRecords")
  async updateDataRecords(
    @common.Param() params: AccountWhereUniqueInput,
    @common.Body() body: DataRecordWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      dataRecords: {
        set: body,
      },
    };
    await this.service.updateAccount({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/dataRecords")
  async disconnectDataRecords(
    @common.Param() params: AccountWhereUniqueInput,
    @common.Body() body: DataRecordWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      dataRecords: {
        disconnect: body,
      },
    };
    await this.service.updateAccount({
      where: params,
      data,
      select: { id: true },
    });
  }
}
